services:
  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      #- xpack.security.http.ssl.enabled=false
      #- xpack.security.enabled=true
      - ELASTIC_PASSWORD=passwd123
      #- xpack.security.enrollment.enabled=true
    ports:
      - "9200:9200"
    networks:
      - elk-net

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk-net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - elk-net


  logstash:
    image: logstash:8.12.2
    container_name: logstash
    restart: always
    ports:
      - "5044:5044"
    environment:
      - NODE_NAME=logstash
      - xpack.monitoring.enabled=false
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
    networks:
      - elk-net


  filebeat:
    image: elastic/filebeat:8.12.2
    container_name: filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      #- ./logs/nginx:/var/log/nginx
    depends_on:
      - elasticsearch
    networks:
      - elk-net

networks:
  elk-net:
    driver: bridge
