#filebeat.inputs:
#  - type: log
#    enabled: true
#    paths:
#      - /var/log/nginx/access.log
#      - /var/log/nginx/error.log

#output.elasticsearch:
#  hosts: ["http://elasticsearch:9200"]
filebeat.inputs:
#  - type: container
  - type: log
    enabled: true
    paths:
      #- /var/lib/docker/containers/*/*.log
      - /var/log/nginx/*.log
      - /home/logstst/logs/nginx/*.log
      - /home/logstst/logs/nginx/access.log
output.logstash:
  enabled: true
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"
  username: "elastic"
  password: "passwd123"

logging.level: debug

#processors:
#  - add_host_metadata: ~
#  - add_cloud_metadata: ~
#  - add_docker_metadata: ~
#  - decode_json_fields:
#      fields: ["message"]
#      target: "json"
