services:
  elasticsearch:
    image: elasticsearch:8.17.0
    restart: always
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=passwd123
      - xpack.license.self_generated.type=basic
      - path.data=/usr/share/elasticsearch/data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elastic

  kibana:
    image: kibana:8.17.0
    restart: always
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - SERVER_NAME=kibana
    networks:
      - elastic
   
networks:
  elastic:
    driver: bridge  
