services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /home/logstst/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/logstst/logs/nginx:/var/log/nginx
    networks:
      - elastic

networks:
  elastic:
